version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - node/test:
          test-results-for: mocha
      - run: node --version
     
workflows:
  test_my_app:
    jobs:
      - node-example
