version: '2.1'
orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.2.5
jobs:
  run-test:
    docker:
      - image: 'cimg/node:18.0.0-browsers'
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: |
          node --version
          java --version
          google-chrome --version
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: npm install
      - run: npx wdio
  print:
    parameters:
      var:
        type: string
    docker:
      - image: 'cimg/node:18.0.0-browsers'
    steps:
      - run: echo "<<parameters.var>>"


workflows:
  test_my_app:
    jobs:
      - run-test
      - print:
         matrix:
          parameters:
           var: [<<pipeline.id>>, <<pipeline.number>>, <<pipeline.project.git_url>>, <<pipeline.project.type>>]
