version: '2.1'
orbs:
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.2.5
jobs:
  run-test:
    docker:
      - image: 'cimg/node:18.0.0-browsers'
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - run: |
          node --version
          java --version
          google-chrome --version
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run: npm install
      - run: npx wdio
      - run: echo "pipeline.id - <<pipeline.id>>"
      - run: echo "pipeline.number - <<pipeline.number>>"
      - run: echo "pipeline.project.git_url - <<pipeline.project.git_url>>"
      - run: echo "pipeline.project.type - <<pipeline.project.type>>"
      - run: echo "pipeline.git.tag - <<pipeline.git.tag>>"
      - run: echo "pipeline.git.branch - <<pipeline.git.branch>>"
      - run: echo "pipeline.git.revision - <<pipeline.git.revision>>"
      - run: echo "pipeline.git.base_revision - <<pipeline.git.base_revision>>"
      - run: echo "pipeline.trigger_source - <<pipeline.trigger_source>>"
      - run: echo "pipeline.schedule.name - <<pipeline.schedule.name>>"
      - run: echo "pipeline.schedule.id - <<pipeline.schedule.id>>"
workflows:
  test_my_app:
    jobs:
      - run-test
